[package]
name = "socketry-concurrent"
version.workspace = true
edition.workspace = true
description = "A cooperative future scheduler with nested stackful waits"
license.workspace = true
repository.workspace = true
readme = "readme.md"
include = ["Cargo.toml", "build.rs", "license.md", "readme.md", "src/**", "examples/**", "vendor/**"]

[lib]
name = "socketry_concurrent"
path = "src/lib.rs"

[features]
address-sanitizer = []
thread-sanitizer = []

[dependencies]
libc = "0.2"

[build-dependencies]
cc = "1"
