name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux x86-64
            runner: ubuntu-24.04
          - name: Linux AArch64
            runner: ubuntu-24.04-arm
          - name: macOS x86-64
            runner: macos-15-intel
          - name: macOS AArch64
            runner: macos-15
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
      - name: Run workspace tests
        run: cargo test --workspace --all-targets --locked

  freebsd:
    name: FreeBSD x86-64
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - name: Run workspace tests in FreeBSD
        uses: vmactions/freebsd-vm@v1
        with:
          release: "15.1"
          prepare: pkg install -y rust
          run: cargo test --workspace --all-targets --locked

  sanitizer:
    name: Linux x86-64 ${{ matrix.name }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: AddressSanitizer
            sanitizer: address
            feature: address-sanitizer
          - name: ThreadSanitizer
            sanitizer: thread
            feature: thread-sanitizer
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src
      - name: Run sanitizer tests
        run: cargo test -Zbuild-std --target x86_64-unknown-linux-gnu --workspace --all-targets --features socketry-concurrent/${{ matrix.feature }} --locked
        env:
          RUSTFLAGS: -Zsanitizer=${{ matrix.sanitizer }}
