name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux x86-64
            runner: ubuntu-24.04
          - name: Linux AArch64
            runner: ubuntu-24.04-arm
          - name: macOS x86-64
            runner: macos-15-intel
          - name: macOS AArch64
            runner: macos-15
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
      - name: Run workspace tests
        run: cargo test --workspace --all-targets --locked

  freebsd:
    name: FreeBSD x86-64
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - name: Run workspace tests in FreeBSD
        uses: vmactions/freebsd-vm@v1
        with:
          release: "15.1"
          prepare: pkg install -y rust
          run: cargo test --workspace --all-targets --locked
